{"1":{"str":"php_pinpoint"},"2":{"str":"PHPApplication"},"3":{"i64":1539930010095},"4":{"str":"ABhwaHBfcGlucG9pbnTv4+zX6Cwi"},"7":{"i64":6293713542711621798},"8":{"i64":-1},"9":{"i64":1539930032452},"10":{"i32":1},"11":{"str":"/test_exception01.php"},"12":{"i16":1500},"13":{"str":"127.0.0.1:8989"},"14":{"str":"127.0.0.1"},"15":{"lst":["rec",2,{"1":{"i32":999},"2":{"rec":{"1":{"str":"/home/liumingyi/git/pinpoint-c-agent/simulate/testcase/php/trace/test_exception01"}}}},{"1":{"i32":300},"2":{"rec":{"11":{"rec":{"1":{"i64":1539930032452},"2":{"i32":2},"3":{"i32":0}}}}}}]},"16":{"i16":0},"17":{"i32":1},"18":{"lst":["rec",0]},"25":{"i32":-13},"26":{"rec":{"1":{"i32":-2},"2":{"str":"Fatal error: Uncaught exception 'Exception' with message 'Error Processing Request' in /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/plugins/test_01_plugin.php:916\nStack trace:\n#0 /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/test_exception01.php(23): TestException01Interceptor->onBefore(139, Array)\n#1 /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/test_exception01.php(34): test_exception01->testFunc('sam')\n#2 {main}\n  thrown in /home/liumingyi/git/pinpoint-c-agent/simulate/web/php/plugins/test_01_plugin.php on line 916"}}}}